//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace small_n_stats_WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("small_n_stats_WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # 
        ///#    Copyright 2016 Shawn Gilroy
        ///#
        ///#    This file is part of Small N Stats.
        ///#
        ///#    Small N Stats is free software: you can redistribute it and/or modify
        ///#    it under the terms of the GNU General Public License as published by
        ///#    the Free Software Foundation, version 2.
        ///#
        ///#    Small N Stats is distributed in the hope that it will be useful,
        ///#    but WITHOUT ANY WARRANTY; without even the implied warranty of
        ///#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        ///#    GNU General  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExponentialDemandFunctions {
            get {
                return ResourceManager.GetString("ExponentialDemandFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # 
        ///#    Copyright 2016 Shawn Gilroy
        ///#
        ///#    This file is part of Small N Stats.
        ///#
        ///#    Small N Stats is free software: you can redistribute it and/or modify
        ///#    it under the terms of the GNU General Public License as published by
        ///#    the Free Software Foundation, version 2.
        ///#
        ///#    Small N Stats is distributed in the hope that it will be useful,
        ///#    but WITHOUT ANY WARRANTY; without even the implied warranty of
        ///#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        ///#    GNU General  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExponentiatedDemandFunctions {
            get {
                return ResourceManager.GetString("ExponentiatedDemandFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2016 Shawn Gilroy
        ///
        ///This file is part of Small N Stats.
        ///
        ///Small N Stats is free software: you can redistribute it and/or modify
        ///it under the terms of the GNU General Public License as published by
        ///the Free Software Foundation, version 2.
        ///
        ///Small N Stats is distributed in the hope that it will be useful,
        ///but WITHOUT ANY WARRANTY; without even the implied warranty of
        ///MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        ///GNU General Public License for more details.
        ///
        ///You should have  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LICENSE {
            get {
                return ResourceManager.GetString("LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		    GNU GENERAL PUBLIC LICENSE
        ///		       Version 2, June 1991
        ///
        /// Copyright (C) 1989, 1991 Free Software Foundation, Inc.
        ///                       51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///			    Preamble
        ///
        ///  The licenses for most software are designed to take away your
        ///freedom to share and change it.  By contrast, the GNU General Public
        ///License is intended to guar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License_ggplot2 {
            get {
                return ResourceManager.GetString("License_ggplot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		    GNU GENERAL PUBLIC LICENSE
        ///		       Version 2, June 1991
        ///
        /// Copyright (C) 1989, 1991 Free Software Foundation, Inc.
        ///                       51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///			    Preamble
        ///
        ///  The licenses for most software are designed to take away your
        ///freedom to share and change it.  By contrast, the GNU General Public
        ///License is intended to guar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License_GNOME_icons {
            get {
                return ResourceManager.GetString("License_GNOME_icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		    GNU GENERAL PUBLIC LICENSE
        ///		       Version 2, June 1991
        ///
        /// Copyright (C) 1989, 1991 Free Software Foundation, Inc.
        ///                       51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///			    Preamble
        ///
        ///  The licenses for most software are designed to take away your
        ///freedom to share and change it.  By contrast, the GNU General Public
        ///License is intended to guar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License_nlmrt {
            get {
                return ResourceManager.GetString("License_nlmrt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		    GNU GENERAL PUBLIC LICENSE
        ///		       Version 2, June 1991
        ///
        /// Copyright (C) 1989, 1991 Free Software Foundation, Inc.
        ///                       51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///			    Preamble
        ///
        ///  The licenses for most software are designed to take away your
        ///freedom to share and change it.  By contrast, the GNU General Public
        ///License is intended to guar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License_nlstools {
            get {
                return ResourceManager.GetString("License_nlstools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		    GNU GENERAL PUBLIC LICENSE
        ///		       Version 2, June 1991
        ///
        /// Copyright (C) 1989, 1991 Free Software Foundation, Inc.
        ///                       59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///			    Preamble
        ///
        ///  The licenses for most software are designed to take away your
        ///freedom to share and change it.  By contrast, the GNU General Public
        ///License is intended to guara [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License_R {
            get {
                return ResourceManager.GetString("License_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New BSD License (BSD)
        ///Copyright (c) 2010, RecycleBin
        ///All rights reserved.
        ///
        ///Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        ///
        ///* Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        ///
        ///* Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License_RdotNet {
            get {
                return ResourceManager.GetString("License_RdotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SNS {
            get {
                object obj = ResourceManager.GetObject("SNS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
